GET http://localhost:3001/api/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmFuZG9tIFBlcnNvbiIsImlkIjoiNWQxOWEyYzA1ZmU3NDkxZTkwZGRkYmU2IiwiaWF0IjoxNTYyMDA1MTI5fQ.Tj1zcEVGMzBXlMX6CnBJ1n53leaOiHP7NmTtm9UcnbU

{}