POST http://localhost:3001/api/workouts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmFuZG9tIFBlcnNvbiIsImlkIjoiNWQxYWY3OTc5M2U5ZTIxOGU0YjBiMGMzIiwiaWF0IjoxNTYyMDU2NzI1fQ.fG_BfqMgNrc7xyX4Z7v_Ia7FrxzhY4Xzq2ZjquHeJnI

{
    "date": "2019-07-03",
    "amount": 5,
    "points": 20,
    "activity": "5d1b32583686df151898b0ca"
}