GET http://localhost:3001/api/users/all/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmFuZG9tIFBlcnNvbiIsImlkIjoiNWQxNzk4MDY1MzY3ZGYyZjI4ZGQwNzA4IiwiaWF0IjoxNTY0Mzg5NDA5fQ.Bwu48istN9IdZL-SIrpdcBAOvwPe6CPw1cq925xqllo