GET http://localhost:3001/api/users/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUmFuZG9tIFBlcnNvbiIsImlkIjoiNWQxYjYyZGM3OWYzMGMzMmVjN2IzMzcyIiwiaWF0IjoxNTYyMDc1ODc2fQ._AtiZuURmiaImWROwzPCrxQjzGerzUwc_FBZLkv0M5Q
