GET http://localhost:3001/api/workouts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGFoYSBWYXN0dXN0YWphIiwiaWQiOiI1ZDFlNzMxODM3ZDgwMzMwNGNmZTAyMGEiLCJpYXQiOjE1NjI5MjQxMjB9.GdQxs2MDHiv8J4NbE0D7KPCrV_LmqrVkGQmzoGHWtqg